from setuptools import setup


setup(name="equibot",
      version="0.1",
      description="",
      author="",
      author_email="",
      license="",
      packages=[],
      install_requires=[
          "click",
          "matplotlib",
          "scipy",
          "tqdm",
          "opencv-python==4.9.0.80",
          "opencv-python-headless==4.9.0.80",
          "opencv-contrib-python==4.7.0.72",
          "hydra-core",
          "wandb",
          "chardet",
          "trimesh[all]",
          "natsort",
          "ffmpeg",
          "imageio[ffmpeg]",
          "ipykernel",
          "robosuite",
          "gtimer",
          "scikit-video",
          "einops",
          "diffusers",
          "gym",
          "pybullet",
          "protobuf==3.20.0",
           "modern-robotics",
           "open3d",
           "h5py",
      ])
