defaults:
  - base

use_wandb: true

training:
  # ckpt: "logs/train/dmg_assembly/ckpt_traj_grasp_bimanual.pth" 
  eval_interval: 10
  num_epochs: 2000

env:
  env_class: 'dmg_assembly'
  num_eef: 2
  dof: 7
  max_episode_length: 50

agent:
  agent_name: eefequibot

model:
  down_dims: [256, 512, 1024]
### use VDGCNN and transfer from pretrained model
  hidden_dim: 256

  obs_horizon: 2
  
  encoder:
    backbone_type: VDGCNN
    backbone_args: 
      num_layers: 7
      preload_path: "pretrained/chairs.pt"

data:
  dataset:
    num_points: 256
    # uniskills: ['grasp', 'contact']
    # skill_names: ['grasp_piece_1', 'grasp_piece_2', 'piece_2_contact_piece_1', 'piece_1_contact_base']
    # conditioned_objects: ['piece_1', 'piece_2', 'piece_1', 'base']
    uniskills: ['grasp']
    skill_names: ['robot0_grasp_piece_1', 'robot1_grasp_piece_2', 'bimanual_0']
    conditioned_objects: ['piece_1', 'piece_2', 'None']
    dataset_type: 'dmg_policy'

    is_obj_centric: True


eval:
  history_bid: 10



