defaults:
  - base

use_wandb: true

training:
  # ckpt: "logs/train/mj_peg_hole/ckpt_mj_traj.pth" 
  eval_interval: 10
  num_epochs: 2000

env:
  env_class: 'dmg_threading'
  num_eef: 2
  dof: 7
  max_episode_length: 50

agent:
  # agent_name: aloha
  # agent_name: compaloha
  agent_name: dmg

model:
### use VDGCNN and transfer from pretrained model
  hidden_dim: 256

  obs_horizon: 1
  
  encoder:
    backbone_type: VDGCNN
    backbone_args: 
      num_layers: 7
      preload_path: "pretrained/chairs.pt"

data:
  dataset:
    num_points: 128
    # uniskills: ['grasp', 'contact']
    # skill_names: ['grasp_piece_1', 'grasp_piece_2', 'piece_2_contact_piece_1', 'piece_1_contact_base']
    # conditioned_objects: ['piece_1', 'piece_2', 'piece_1', 'base']
    uniskills: ['grasp']
    skill_names: ['robot0_grasp_tripod_obj', 'robot1_grasp_needle_obj', 'bimanual_0']
    conditioned_objects: ['tripod_obj', 'needle_obj', 'None']
    dataset_type: 'dexmimicgen'

    is_obj_centric: True


eval:
  history_bid: 10



