defaults:
  - base

use_wandb: true

training:
  # ckpt: "logs/train/dmg_threading/2025-07-03_21-13-09/checkpoints/ckpt00400.pth" 
  eval_interval: 10
  num_epochs: 2000
  batch_size: 32

env:
  env_class: 'dmg_threading'
  num_eef: 2
  dof: 7
  max_episode_length: 50

agent:
  # agent_name: aloha
  # agent_name: compaloha
  agent_name: dmg

model:
  down_dims: [128, 256, 512]
### use VDGCNN and transfer from pretrained model
  hidden_dim: 256
  obs_horizon: 1
  pred_horizon: 8

  separate_encoder: False
  separate_policy: False
  # noise_scheduler:
  #   _target_: diffusers.schedulers.scheduling_ddim.DDIMScheduler
  # num_diffusion_iters: 15 ## inference for DDIM

  encoder:
    backbone_type: VDGCNN
    backbone_args: 
      num_layers: 7
      preload_path: "pretrained/chairs.pt"

  embedding_cache_dir: "./data/bert"

  language_encoder_cfg:
    network_name: MLPEncoder
    input_size: 768
    hidden_size: 256
    num_layers: 1

data:
  dataset:
    num_points: 256
    # uniskills: []
    # skill_names: ['bimanual_0']
    # conditioned_objects: ['None']
    uniskills: ['grasp']
    skill_names: ['robot0_grasp_tripod_obj', 'robot1_grasp_needle_obj', 'bimanual_0']
    conditioned_objects: ['tripod_obj', 'needle_obj', 'None']
    dataset_type: 'robosuite_separate_hdf5_traj'

    is_obj_centric: True
    is_add_bottom: True
    downsample_method: 'fps'
    rot_aug: True

eval:
  history_bid: 10



