defaults:
  - base

use_wandb: true
wandb_node: null

training:
  # ckpt: "logs/train/mj_peg_hole/ckpt_mj_traj.pth" 
  eval_interval: 50
  num_epochs: 2000

env:
  env_class: 'libero_spatial'
  num_eef: 2
  dof: 7
  max_episode_length: 50

agent:
  agent_name: dmg

model:
  down_dims: [128, 256, 512]
### use VDGCNN and transfer from pretrained model
  hidden_dim: 256

  obs_horizon: 1
  pred_horizon: 8
  
  separate_encoder: False
  separate_policy: True

  encoder:
    backbone_type: VDGCNN
    backbone_args: 
      num_layers: 7
      preload_path: "pretrained/mugs.pt"

  embedding_cache_dir: "./data/bert"

  language_encoder_cfg:
    network_name: MLPEncoder
    input_size: 768
    hidden_size: 256
    num_layers: 1

data:
  dataset:
    num_points: 128
    primitive_kws: ['grasp', 'place']
    skill_names: ['robot0_grasp_akita_black_bowl_1', 'robot0_place_akita_black_bowl_1_plate_1']
    conditioned_objects: ['akita_black_bowl_1', 'plate_1']
    dataset_type: 'robosuite_integrate_hdf5_traj'

    embedding_cache_dir: "./data/bert"
    eef_representation: "3vec"

    is_obj_centric: True
    is_add_bottom: True 
    downsample_method: 'fps'
    rot_aug: True
    n_use: 20

eval:
  history_bid: 10



