defaults:
  - base

use_wandb: true
wandb_note: null

training:
  # ckpt: "logs/train/libero_per_skill/2025-08-10_11-32-49/checkpoints/ckpt_3vec.pth" 
  eval_interval: 10
  num_epochs: 2000

env:
  env_class: 'libero_per_skill'
  num_eef: 2
  dof: 7
  max_episode_length: 50

agent:
  agent_name: per_skill

model:
  down_dims: [128, 256, 512]
### use VDGCNN and transfer from pretrained model
  hidden_dim: 256

  obs_horizon: 1
  pred_horizon: 8
  
  separate_encoder: False
  separate_policy: False

  encoder:
    backbone_type: VDGCNN
    backbone_args: 
      num_layers: 7
      preload_path: "pretrained/mugs.pt"


  language_encoder_cfg:
    network_name: MLPEncoder
    input_size: 768
    hidden_size: 256
    num_layers: 1

data:
  dataset:
    num_points: 128
    uniskills: ['grasp', 'place']
    # skill_names: ['robot0_grasp_akita_black_bowl_1', 'robot0_place_akita_black_bowl_1_plate_1']
    # conditioned_objects: ['akita_black_bowl_1', 'plate_1']
    dataset_type: 'per_skill_traj'

    is_obj_centric: True
    is_add_bottom: True 
    downsample_method: 'fps'
    rot_aug: True

    embedding_cache_dir: "./data/bert"
    task_suite_name: "libero_spatial"
    n_use: 50

    # eef_representation: "4pts"
    eef_representation: "3vec"

    normalization_method: "all"
    choose_id_method: "normal"

    original_gripper_pcd: [[0.10, 0.01, 0], 
                            [0.03, -0.04, 0],
                            [0.02, 0.05, 0],
                            [0,0,0]]
    # original_gripper_pcd: [[ 5.34803828e-04, -2.65891908e-03, -6.49434167e-02],
    #                         [ 3.48747446e-04,  4.88699045e-02, -2.86211470e-02],
    #                         [ 8.89648299e-05, -5.10463244e-02, -2.45325339e-02],
    #                         [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00]]

eval:
  history_bid: 10



