defaults:
  - base

use_wandb: true
wandb_note: "Equibot training on real ALOHA data"

training:
  # ckpt: "logs/train/screwdriver_fresh/ckpt_best.pth"
  eval_interval: 50
  num_epochs: 2000
env:
  env_class: 'per_skill_real_aloha'
  num_eef: 2
  dof: 7
  max_episode_length: 50

agent:
  agent_name: per_skill

model:
  down_dims: [128, 256, 512]

  obs_horizon: 1
  pred_horizon: 8
  
  separate_encoder: False
  separate_policy: False

  fuse_inv_feat: True

### use VDGCNN and transfer from pretrained model
  hidden_dim: 256
  encoder:
    backbone_type: VDGCNN
    backbone_args: 
      num_layers: 7
      preload_path: "pretrained/chairs.pt"

  language_encoder_cfg:
    network_name: MLPEncoder
    input_size: 768
    hidden_size: 256
    num_layers: 1

data:
  dataset:
    path: null  # Set via command line, e.g., data/handoff_cup
    task_name: null  # Set via command line, e.g., handoff_cup (optional if use_task_name=false)
    num_points: 128
    
    uniskills: ['grasp']  # Skills to extract from data
    # uniskills: ['grasp']
    dataset_type: 'real_aloha_traj'  # Use real ALOHA dataset
    
    # uniskills: ['bimanual']
    # dataset_type: 'real_aloha_biop_jpose'
    
    is_obj_centric: True
    is_add_bottom: True 
    downsample_method: 'fps'
    rot_aug: True


    
    embedding_cache_dir: "./data/bert"
    
    # Action representation
    # 3vec: position + 2 rotation vectors (equivariant)
    # 4pts: 4 keypoints on gripper
    eef_representation: "3vec"
    
    normalization_method: "all"
    
    original_gripper_pcd: [[0.10, 0.01, 0], 
                            [0.03, -0.04, 0],
                            [0.02, 0.05, 0],
                            [0, 0, 0]]

    use_pc_color: False               # Use RGB color in point cloud 
    aug_traj_nums: 4

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    agentview_image:
      shape: [3, 128, 128]
      type: rgb
    robot0_eye_in_hand_image:
      shape: [3, 128, 128]
      type: rgb
    robot0_eef_pos:
      shape: [3]
      # type default: low_dim
    robot0_eef_quat:
      shape: [4]
    robot0_gripper_qpos:
      shape: [2]

  action: 
    shape: [14]


eval:
  history_bid: 10



