defaults:
  - base

use_wandb: true

training:
  # ckpt: "/home/user/yzchen_ws/docker_share_folder/difussion/equibot_abstract/logs/train/screwdriver_fresh/ckpt_best.pth"
  eval_interval: 1

env:
  env_class: 'screwdriver'
  num_eef: 2
  # dof: 6 # aloha
  dof: 7
  max_episode_length: 50


agent:
  agent_name: aloha

model:
  # noise_scheduler:
  #   num_train_timesteps: 1000

# ## use vec_pointnet and train from scratch
#   hidden_dim: 32
#   encoder:
#     backbone_type: vn_pointnet
#     backbone_args: 
#       num_layers: 4
#       preload_path: 'None' 


### use VDGCNN and transfer from pretrained model
  hidden_dim: 256
  encoder:
    backbone_type: VDGCNN
    backbone_args: 
      num_layers: 7
      preload_path: "/home/robotics/CoMa_code_clean/equibot_abstract/pretrained/kit4cates.pt"

data:
  dataset:
    num_points: 128
    symb_mask: ['qpose_left', 'qpose_right', 'grasp_left', None, None]

    tamp_type: 'precondition'
    dataset_type: 'hdf5_mini'
    has_eff: false

    is_obj_centric: true

    preload_path: ${model.encoder.backbone_args.preload_path}


eval:
  history_bid: 10



