defaults:
  - base

use_wandb: true

training:
  # ckpt: "/home/user/yzchen_ws/docker_share_folder/difussion/equibot_abstract/logs/train/aloha_transfer_tape/ckpt00100.pth"
  eval_interval: 1

env:
  env_class: 'tape'
  dof: 6
  max_episode_length: 50

agent:
  agent_name: aloha

model:
  encoder:
    backbone_type: vn_pointnet

data:
  dataset:
    num_points: 512
    # symb_mask: ['qpose_left', 'qpose_right', None, 'grasp_right', None]
    symb_mask: [None, None, None, 'grasp_right', None]
    tamp_type: 'precondition'
    dataset_type: 'hdf5'

eval:
  history_bid: 10



