defaults:
  - base

use_wandb: false

training:
  ckpt: "/home/xuhang/Desktop/yzchen_ws/equibot_abstract/logs/train/aloha_transfer_tape/ckpt_best.pth"
  eval_interval: 1

env:
  env_class: 'tape'
  num_eef: 2
  dof: 6
  max_episode_length: 50

agent:
  agent_name: aloha

model:
  # noise_scheduler:
  #   num_train_timesteps: 1000
  encoder:
    backbone_type: vn_pointnet
    backbone_args: 
      num_layers: 4
data:
  dataset:
    num_points: 512
    # symb_mask: ['qpose_left', 'qpose_right', None, None, None]
    symb_mask: ['qpose_left', 'qpose_right', None, 'grasp_right', None]
    # symb_mask: [None, 'qpose_right', None, 'grasp_right', None]
    # symb_mask: [None, None, None, 'grasp_right', None]
    tamp_type: 'precondition'
    dataset_type: 'hdf5_predeff'
    # dataset_type: 'hdf5'


eval:
  history_bid: 10



