defaults:
  - base

use_wandb: false

training:
  ckpt: "/home/user/yzchen_ws/docker_share_folder/difussion/equibot_abstract/logs/train/aloha_transfer_tape/ckpt00300.pth.enc4layer"
  eval_interval: 1

env:
  env_class: 'tape'
  num_eef: 2
  dof: 6
  max_episode_length: 50

agent:
  agent_name: aloha

model:
  encoder:
    backbone_type: vn_pointnet
    # backbone_args: 
    #   num_layers: 2
data:
  dataset:
    num_points: 512
    symb_mask: ['qpose_left', 'qpose_right', None, 'grasp_right', None]
    # symb_mask: [None, None, None, 'grasp_right', None]
    tamp_type: 'precondition'
    dataset_type: 'hdf5'

eval:
  history_bid: 10



